export const GET_QUOTE = 'GET_QUOTE'
export const GET_QUOTE_IS_LOADING = 'GET_QUOTE_IS_LOADING'
export const GET_QUOTE_DID_ERROR = 'GET_QUOTE_DID_ERROR'
export const GET_QUOTE_SUCESS = 'GET_QUOTE_SUCESS'
